name: WP Full Audit

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target website URL (e.g. https://example.com)'
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run WP Full Audit
        run: |
          mkdir -p reports
          python wpscan.py --target "${{ github.event.inputs.target_url }}" --pretty --output-dir reports --wpscan-key ${{ secrets.WPSCAN_KEY }}

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: wp-audit-reports
          path: reports/
